Dev-Z
Glabay/Glabay-Studios-Server pull request #5
Opened 2024-10-05 14:19 UTC by Zeighe

help

2024-10-05 14:34 UTC, Glabay requested changes

2024-10-05 14:34 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/alkharid/duelarena/SurgeonGeneralTafani.java
> +        player.getDH().sendItemStatement("Restored your HP, Prayer, Run Energy, and Spec", 4049);
Magic number can be replaced with Items.ITEM_NAME

2024-10-05 14:34 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/canifis/Mazchna.java
> +            player.getDH().sendNpcChat2("Do not waste my time peasent.", "You need a Combat level of 20.", 402, "Mazchna");
NPC ID 402 can be replaced with the MAZCHNA

2024-10-05 14:34 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/canifis/Mazchna.java
> +            player.getDH().sendDialogues(180, MAZCHNA);
the Dialogue ID can be added to the Dialogues.java class

2024-10-05 14:34 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/global/MasterFarmer.java
> +            player.getShops().openShop(16);
Perhaps we can make a `Shops.java` to hold the shop IDs to not have Magic numbers... Hmm

2024-10-05 14:34 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/tutorialisland/CombatInstructor.java
> +        player.getPA().showInterface(37700);
Hmm maybe we need an `Interfaces.java` for these Magic Numbers

2024-10-06 01:59 UTC, Glabay requested changes

2024-10-06 01:59 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/taverly/dungeon/KeyMaster.java
> +            player.getSlayer().createNewTask(5870, true);
This is a Magic Number

2024-10-08 15:03 UTC, Glabay requested changes

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/content/bosses/grotesqueguardians/GrotesqueInstance.java
> -            GrotesqueGuardianNpc dusk = new GrotesqueGuardianNpc(Npcs.DUSK_2, new Position(1692, 4576, getHeight()), this);
These are preparing the 2 Bosses, Dusk and Dawn, and you have the same ID for both here

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/content/bosses/grotesqueguardians/GrotesqueGuardianNpc.java
> -                    requestTransform(Npcs.DUSK_4);
This ID Changed from 7854 to 7855, was this intentional?

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/content/bosses/grotesqueguardians/GrotesqueGuardianNpc.java
> -        if (getNpcId() == Npcs.DAWN_3 || getNpcId() == Npcs.DUSK_4)
DUSK_4 changed from 7854 to 7855

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/global/makeovermage.java
>  public class makeovermage extends NpcOptionAction {
The Name of this class is wrong, should be CameCase  `MakeoverMage`

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/global/makeovermage.java
> -            player.getPA().showInterface(3559);
Looks like you replaced an Interface.MAKEOVER_MAGE_INTERFACE with a Magic Number? Why?

2024-10-08 15:03 UTC, Glabay commented on src/main/java/io/xeros/model/entity/npc/interactions/impl/lumbridge/LumbridgeGuide.java
> -        player.getDH().sendDialogues(710, 306);
Looks like you removed the Constants and added Magic Numbers

used to be `LUMBRIDGE_GUIDE_DIALOGUE, LUMBRIDGE_GUIDE`

2024-10-08 15:49 UTC, Zeighe commented on src/main/java/io/xeros/content/bosses/grotesqueguardians/GrotesqueGuardianNpc.java
> -                    requestTransform(Npcs.DUSK_4);
Yeah bb

2024-10-08 15:56 UTC, Glabay approved these changes

2024-10-08 15:57 UTC, merged